### ISSUE TITLE
Web Jars bower github

### ISSUE THREAD

**Issue by syndybat** [fsx950223/chartjs-web-components#2]
Hi,
I would like to make vaadin 10+ plugin for chartjs by wrapping your webcompoment.
But I struggle to get a webjar from bower github at https://www.webjars.org/.

If you try add webjar to bower github from your repository it fails because it can not find @polymer/lit-element on github. I forked your repository and changed @polymer/lit-element to polymer/lit-element in package.json url: https://github.com/syndybat/chartjs-web-components. Then I was able to ad webjar to bower github. But when I add it in my project as maven dependency it cannot find correct version of polymer/lit-element. Start project to create a plugin is https://vaadin.com/start/lts/component. I tried to add another version to @polymer/lit-element on webjars page but it also failed.

I am not so skilled in this area. Would you be kind and look into it so the dependency problem would be solved?

Petr

**Comment by syndybat** [comment]
there is a tutorial how to create a plugin https://vaadin.com/docs/v10/flow/web-components/integrating-a-web-component.html

**Comment by fsx950223** [comment]
> Hi,
> I would like to make vaadin 10+ plugin for chartjs by wrapping your webcompoment.
> But I struggle to get a webjar from bower github at https://www.webjars.org/.
> 
> If you try add webjar to bower github from your repository it fails because it can not find @polymer/lit-element on github. I forked your repository and changed @polymer/lit-element to polymer/lit-element in package.json url: https://github.com/syndybat/chartjs-web-components. Then I was able to ad webjar to bower github. But when I add it in my project as maven dependency it cannot find correct version of polymer/lit-element. Start project to create a plugin is https://vaadin.com/start/lts/component. I tried to add another version to @polymer/lit-element on webjars page but it also failed.
> 
> I am not so skilled in this area. Would you be kind and look into it so the dependency problem would be solved?
> 
> Petr

Lit-element has not published to bower.Maybe you should open a issue in polymer/lit-element

**Comment by fsx950223** [comment]
![1](https://user-images.githubusercontent.com/17592563/45731235-2e298280-bc09-11e8-9c98-c5dc0cde7dcb.png)
If I use npm,it will be depolyed.

**Comment by syndybat** [comment]
Yes I know I also tried that but I need to use bower githhub. Thank I will raise issue for lit-element
