### ISSUE TITLE
Unable to compile TypeScript

### ISSUE THREAD

**Issue by scenaristeur** [fsx950223/chartjs-web-components#3]
after a git clone, 
npm install return me
```
TSError: ⨯ Unable to compile TypeScript:
config/production.config.ts(5,31): error TS2307: Cannot find module 'compression-webpack-plugin'.
```
perharps ' compression-webpack-plugin ' should be added to package.json ?

**Comment by fsx950223** [comment]
> after a git clone,
> npm install return me
> 
> ```
> TSError: ⨯ Unable to compile TypeScript:
> config/production.config.ts(5,31): error TS2307: Cannot find module 'compression-webpack-plugin'.
> ```
> perharps ' compression-webpack-plugin ' should be added to package.json
